# Файл docker-compose.yml

version: '3'

# Перечень volume
volumes:
  pg_data:

  static:

# Перечень контейнеров
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
    build: ./frontend/ 
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - db
